# Generated by Django 5.1.3 on 2025-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
