# Generated by Django 5.1.3 on 2025-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_companyprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='catalog',
            field=models.FileField(blank=True, null=True, upload_to='company_catalogues/'),
        ),
    ]
