# Generated by Django 5.1.3 on 2025-03-11 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='company_presentations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='catalog',
            field=models.FileField(blank=True, null=True, upload_to='company_catalogues/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
