# Generated by Django 5.1.3 on 2025-03-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_companyprofile_presentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
