# Generated by Django 5.1.3 on 2025-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_companyprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
