# Generated by Django 5.1.3 on 2025-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_companyprofile_facebook_companyprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, default='Georgia', max_length=1500, null=True),
        ),
    ]
