# Generated by Django 5.1.3 on 2025-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('sellers', '0010_branchcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='cities',
            field=models.ManyToManyField(related_name='companies', to='regions.city'),
        ),
    ]
