# Generated by Django 5.1.3 on 2024-12-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
