# Generated by Django 5.1.3 on 2024-12-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerCategory',
        ),
    ]
