# Generated by Django 5.1.3 on 2024-12-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
