# Generated by Django 5.1.3 on 2025-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('source_language', models.CharField(choices=[('en', 'English'), ('ka', 'Georgian'), ('ru', 'Russian')], max_length=2)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('ka', 'Georgian'), ('ru', 'Russian')], max_length=2)),
                ('translated_text', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['text', 'target_language'], name='products_tr_text_4d1dfd_idx')],
            },
        ),
    ]
