# Generated by Django 5.1.3 on 2025-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'ნაჭერი'), ('ml', 'მილილიტრი'), ('gram', 'გრამი'), ('kg', 'კილოგრამი')], default='piece', max_length=10),
        ),
    ]
